name: Test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the application
        run: g++ -Wall -std=c++17 *.cpp -o main
      - name: Run test script
        run: sh ./test.sh main output.txt